swagger: '2.0'
info:
  description: ''
  version: 0.1.0
  title: Auction Price Tracker API
host: auction-price-track-server.herokuapp.com
basePath: /api
schemes:
  - https
paths:
  /recipes:
    get:
      tags:
        - recipes
      summary: Gets all recipes managed by Auction Price Tracker
      description: ''
      operationId: getRecipes
      produces:
        - application/json
      responses:
        '200':
          description: Operation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Recipe'
            example:
              - isCustom: true
                professions:
                  - alchemy
                  - inscription
                _id: 5bad6b59dcf0e92f30d04312
                reagents:
                  - _id: 5bad6b59dcf0e92f30d04319
                    blizzardId: 152510
                    quantity: 1
                    name: Anchor Weed
                    name_fr: Ancoracée
                  - _id: 5bad6b59dcf0e92f30d04318
                    blizzardId: 152507
                    quantity: 1
                    name: Akunda's Bite
                    name_fr: Mâche d’Akunda
                  - _id: 5bad6b59dcf0e92f30d04317
                    blizzardId: 152511
                    quantity: 1
                    name: Sea Stalk
                    name_fr: Brin-de-mer
                  - _id: 5bad6b59dcf0e92f30d04316
                    blizzardId: 152508
                    quantity: 1
                    name: Winter's Kiss
                    name_fr: Bise-d’hiver
                  - _id: 5bad6b59dcf0e92f30d04315
                    blizzardId: 152505
                    quantity: 1
                    name: Riverbud
                    name_fr: Rivebulbe
                  - _id: 5bad6b59dcf0e92f30d04314
                    blizzardId: 152509
                    quantity: 1
                    name: Siren's Pollen
                    name_fr: Pollen de sirène
                  - _id: 5bad6b59dcf0e92f30d04313
                    blizzardId: 152506
                    quantity: 1
                    name: Star Moss
                    name_fr: Mousse étoilée
                __v: 0
              - isCustom: false
                professions:
                  - alchemy
                _id: 5bad6b59dcf0e92f30d0431b
                type: flask
                craft:
                  _id: 5bad6b59dcf0e92f30d0431c
                  blizzardId: 152641
                  quantity: 1
                  name: Flask of the Undertow
                  name_fr: Flacon du ressac
                reagents:
                  - _id: 5bad6b59dcf0e92f30d0431f
                    blizzardId: 152510
                    quantity: 5
                    name: Anchor Weed
                    name_fr: Ancoracée
                  - _id: 5bad6b59dcf0e92f30d0431e
                    blizzardId: 152507
                    quantity: 10
                    name: Akunda's Bite
                    name_fr: Mâche d’Akunda
                  - _id: 5bad6b59dcf0e92f30d0431d
                    blizzardId: 152509
                    quantity: 15
                    name: Siren's Pollen
                    name_fr: Pollen de sirène
                __v: 0
        '500':
          description: Server broken
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unfortunate things happened
  /items:
    get:
      tags:
        - items
      summary: Gets all items managed by Auction Price Tracker
      operationId: getItems
      produces:
        - application/json
      responses:
        '200':
          description: Operation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
            example:
              - _id: 5bad6b58dcf0e92f30d0430b
                blizzardId: 152510
                name: Anchor Weed
                name_fr: Ancoracée
                __v: 0
              - _id: 5bad6b58dcf0e92f30d0430c
                blizzardId: 152507
                name: Akunda's Bite
                name_fr: Mâche d’Akunda
                __v: 0
        '500':
          description: Server broken
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unfortunate things happened
  /realms:
    get:
      tags:
        - realms
      summary: Gets all realms managed by Auction Price Tracker
      operationId: getRealms
      produces:
        - application/json
      responses:
        '200':
          description: Operation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Realm'
            example:
              - _id: 5b82db8eaf83190564444808
                value: arakarahm
                label: Arak-arahm
                __v: 0
              - _id: 5b82db8eaf83190564444809
                value: arathi
                label: Arathi
                __v: 0
              - _id: 5b82db8eaf8319056444480a
                value: archimonde
                label: Archimonde
                __v: 0
        '500':
          description: Server broken
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unfortunate things happened
  /itemstats/{realm}/{itemId}:
    get:
      tags:
        - itemstats
      summary: Gets all item statistics for a specific item in a realm
      parameters:
        - in: path
          name: realm
          required: true
          type: string
          description: the realm slug to get the itemstats from.
        - in: path
          name: itemId
          required: true
          type: integer
          description: the item to get the itemstats for.
        - in: query
          name: start
          required: false
          type: string
          description: start date parameter for the search. The string must be in the ISO 8601 format. If not specified, it starts 28 days before the call day at midnight UTC
        - in: query
          name: end
          required: false
          type: string
          description: end date parameter for the search. The string must be in the ISO 8601 format. If not specified, it ends at the call timestamp
      operationId: getItemStats
      produces:
        - application/json
      responses:
        '200':
          description: Operation successful
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemStat'
            example:
              - _id: 5c631449362bce29f8c0d337
                itemId: 152505
                itemCount: 6212
                mean: 945108
                median: 449998
                max: 3000000
                min: 379999
                mode: 449998
                percentile5: 449997
                percentile25: 451499
                percentile75: 454848
                percentile95: 3000000
                timestamp: '2019-02-12T18:25:14.000Z'
                weekday: Tuesday
                realm: sargeras
                __v: 0
              - _id: 5c6320b8362bce29f8c0da18
                itemId: 152505
                itemCount: 8675
                mean: 1040267
                median: 449998
                max: 3000000
                min: 419000
                mode: 449997
                percentile5: 449997
                percentile25: 453000
                percentile75: 454848
                percentile95: 3000000
                timestamp: '2019-02-12T19:35:14.000Z'
                weekday: Tuesday
                realm: sargeras
                __v: 0
              - _id: 5c6330af362bce29f8c0e1c1
                itemId: 152505
                itemCount: 8775
                mean: 1033540
                median: 449998
                max: 3000000
                min: 419000
                mode: 449997
                percentile5: 449997
                percentile25: 453000
                percentile75: 454848
                percentile95: 3000000
                timestamp: '2019-02-12T20:45:14.000Z'
                weekday: Tuesday
                realm: sargeras
                __v: 0
              - _id: 5c6359ac3b252b30fcdbc686
                itemId: 152505
                itemCount: 8753
                mean: 1033853
                median: 449998
                max: 3000000
                min: 399900
                mode: 449997
                percentile5: 449997
                percentile25: 454848
                percentile75: 3000000
                percentile95: 3000000
                timestamp: '2019-02-12T23:05:14.000Z'
                weekday: Wednesday
                realm: sargeras
                __v: 0
        '500':
          description: Server broken
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unfortunate things happened
definitions:
  Item:
    type: object
    properties:
      _id:
        type: string
      blizzardId:
        type: integer
      name:
        type: string
      name_fr:
        type: string
      __v:
        type: integer
  Realm:
    type: object
    properties:
      _id:
        type: string
      slug:
        type: string
      name:
        type: string
      __v:
        type: integer
  Recipe:
    type: object
    properties:
      _id:
        type: string
      isCustom:
        type: boolean
      professions:
        type: array
        items:
          type: string
          enum:
            - alchemy
            - blacksmithing
            - enchant
            - engineering
            - herbalism
            - inscription
            - jewelcrafting
            - leatherworking
            - mining
            - skinning
            - tailoring
            - cooking
      type:
        type: string
        enum:
          - flask
          - potion
          - ring
          - weapon
          - gem
          - war scroll
          - vantus
          - tome
      craft:
        type: object
        properties:
          _id:
            type: string
          blizzardId:
            type: integer
          quantity:
            type: integer
          name:
            type: string
          name_fr:
            type: string
      reagents:
        type: array
        items:
          type: object
          properties:
            _id:
              type: string
            blizzardId:
              type: integer
            quantity:
              type: integer
            name:
              type: string
            name_fr:
              type: string
      __v:
        type: integer
  ItemStat:
    type: object
    properties:
      _id:
        type: string
      itemId:
        type: integer
      minPrice:
        type: integer
      maxPrice:
        type: integer
      averagePrice:
        type: integer
      timestamp:
        type: string
        description: "A timestamp in the ISO Format"
      realm:
        type: string
      __v:
        type: integer
